CREATE TABLE IF NOT EXISTS events (
	id BYTEA PRIMARY KEY,
	name VARCHAR NOT NULL,
	aggregate_id VARCHAR NOT NULL,
	aggregate_type VARCHAR NOT NULL,
	data JSONB,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
