CREATE TABLE IF NOT EXISTS cards (
	id UUID PRIMARY KEY,
	user_id VARCHAR UNIQUE NOT NULL,
	number VARCHAR UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
